#!/usr/bin/env python3
"""Generate kavach/src/data/40-who-lms.js from the WHO Child Growth Standards
LMS tables shipped in the WHO `anthro` R package (data-raw/growthstandards/*.txt,
https://github.com/WorldHealthOrganization/anthro).

Usage:  python3 -I kavach/tools/gen_who_lms.py <dir-with-who-txt-files> kavach/src/data/40-who-lms.js

Compaction: age tables (days 0-1826) are sampled daily to day 42, then every 7 days plus the last
day, and split at day 730/731 where the length/height table switches from
recumbent length to standing height. Weight-for-length (45-110 cm) and
weight-for-height (65-120 cm) are sampled every 0.5 cm. The app interpolates
L, M and S linearly between samples; `--check` compares against the full
daily tables (max |dz| is printed).
"""
import sys, json, math, random

def load(path):
    rows = []
    with open(path) as f:
        head = f.readline().strip().split('\t')
        for line in f:
            p = line.strip().split('\t')
            if len(p) < 5: continue
            rows.append({head[i]: p[i] for i in range(len(head))})
    return rows

def by_sex(rows, key):
    out = {1: [], 2: []}
    for r in rows:
        out[int(r['sex'])].append((float(r[key]), float(r['l']), float(r['m']), float(r['s']), r.get('loh') or r.get('lorh')))
    for s in out: out[s].sort()
    return out

def sample_age(tab, segments):
    """tab: list of (age, L, M, S, loh); segments: list of (lo, hi) inclusive day ranges"""
    idx = {int(a): (a, L, M, S) for a, L, M, S, _ in tab}
    out = []
    for lo, hi in segments:
        # daily for the first six weeks (weight dips and recovers fast after birth), weekly after
        days = list(range(lo, min(hi, 42) + 1)) + list(range(max(lo, 49), hi + 1, 7)) if lo == 0 else list(range(lo, hi + 1, 7))
        if days[-1] != hi: days.append(hi)
        seg = [[d, idx[d][1], idx[d][2], idx[d][3]] for d in days]
        out.append(seg)
    return out

def sample_len(tab, lo, hi, step=0.5):
    idx = {round(a, 1): (a, L, M, S) for a, L, M, S, _ in tab}
    out = []
    x = lo
    while x <= hi + 1e-9:
        r = idx[round(x, 1)]
        out.append([round(x, 1), r[1], r[2], r[3]])
        x += step
    return out

def fmt(v):
    s = ('%.5f' % v).rstrip('0').rstrip('.')
    return s if s not in ('-0', '') else '0'

def js_arr(rows):
    return '[' + ','.join('[' + ','.join(fmt(x) for x in r) + ']' for r in rows) + ']'

def interp(rows, x):
    if x < rows[0][0] or x > rows[-1][0]: return None
    for i in range(len(rows) - 1):
        a, b = rows[i], rows[i + 1]
        if a[0] <= x <= b[0]:
            t = 0 if b[0] == a[0] else (x - a[0]) / (b[0] - a[0])
            return [a[j] + (b[j] - a[j]) * t for j in (1, 2, 3)]
    return rows[-1][1:4]

def z(y, L, M, S, restricted):
    zz = math.log(y / M) / S if abs(L) < 1e-7 else ((y / M) ** L - 1) / (L * S)
    if restricted:
        sd = lambda k: M * (1 + L * S * k) ** (1 / L) if abs(L) > 1e-7 else M * math.exp(S * k)
        if zz > 3: zz = 3 + (y - sd(3)) / (sd(3) - sd(2))
        elif zz < -3: zz = -3 + (y - sd(-3)) / (sd(-2) - sd(-3))
    return zz

def main():
    src, out = sys.argv[1], sys.argv[2]
    check = '--check' in sys.argv
    T = {}
    wei = by_sex(load(f'{src}/weianthro.txt'), 'age')
    hc = by_sex(load(f'{src}/hcanthro.txt'), 'age')
    ln = by_sex(load(f'{src}/lenanthro.txt'), 'age')
    bmi = by_sex(load(f'{src}/bmianthro.txt'), 'age')
    wfl = by_sex(load(f'{src}/wflanthro.txt'), 'length')
    wfh = by_sex(load(f'{src}/wfhanthro.txt'), 'height')
    for s in (1, 2):
        T[('wfa', s)] = sample_age(wei[s], [(0, 1826)])
        T[('hcfa', s)] = sample_age(hc[s], [(0, 1826)])
        T[('lhfa', s)] = sample_age(ln[s], [(0, 730), (731, 1826)])
        T[('bfa', s)] = sample_age(bmi[s], [(0, 730), (731, 1826)])
        T[('wfl', s)] = [sample_len(wfl[s], 45, 110)]
        T[('wfh', s)] = [sample_len(wfh[s], 65, 120)]
    lines = ['/* Generated by tools/gen_who_lms.py — WHO Child Growth Standards (2006) LMS tables',
             '   from the WHO anthro package. Do not edit by hand. Indexed [x, L, M, S]; x = age in',
             '   days (wfa, lhfa, hcfa, bfa) or length/height in cm (wfl, wfh). sex: 1 = boy, 2 = girl.',
             '   lhfa and bfa have two segments: recumbent length (0–730 d) and standing height (731–1826 d). */',
             'K.who = {']
    for ind in ('wfa', 'lhfa', 'wfl', 'wfh', 'hcfa', 'bfa'):
        lines.append(f'  {ind}: {{')
        for s in (1, 2):
            segs = T[(ind, s)]
            lines.append(f'    {s}: [' + ','.join(js_arr(seg) for seg in segs) + '],')
        lines.append('  },')
    lines.append('};')
    open(out, 'w').write('\n'.join(lines) + '\n')
    print('wrote', out, sum(len(l) for l in lines) // 1024, 'KB')

    if check:
        random.seed(7); worst = {}
        full = {'wfa': wei, 'hcfa': hc, 'lhfa': ln, 'bfa': bmi, 'wfl': wfl, 'wfh': wfh}
        for ind, tab in full.items():
            w = 0
            for s in (1, 2):
                rows = tab[s]
                segs = T[(ind, s)]
                for _ in range(3000):
                    r = random.choice(rows)
                    x = r[0]
                    seg = next((g for g in segs if g[0][0] <= x <= g[-1][0]), None)
                    if seg is None: continue
                    L, M, S = interp(seg, x)
                    y = r[2] * (1 + r[1] * r[3] * random.uniform(-3.5, 3.5)) ** (1 / r[1]) if abs(r[1]) > 1e-7 else r[2]
                    if y <= 0: continue
                    restricted = ind in ('wfa', 'wfl', 'wfh', 'bfa')
                    w = max(w, abs(z(y, L, M, S, restricted) - z(y, r[1], r[2], r[3], restricted)))
            worst[ind] = w
        print('max |dz| vs daily tables:', json.dumps({k: round(v, 4) for k, v in worst.items()}))

if __name__ == '__main__':
    main()
